---
- name: Deploy Python web server
  hosts: all
  become: true
  vars:
    python_packages:
      - python3
      - python3-pip
    required_modules:
      - ssl
      - os
      - sys
      - threading
      - subprocess
      - datetime
  tasks:
    - name: Install php-cgi
      apt:
        name: php-cgi
        state: present

    - name: Copy Python web server code to server
      copy:
        src: server.py
        dest: /usr/local/bin/
        mode: 0755

    - name: Create systemd service file for web server
      template:
        src: server.service.j2
        dest: /etc/systemd/system/server.service
        mode: '0644'
      notify: Reload systemd

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start web server
      systemd:
        name: server
        state: started
        enabled: yes


